### ISSUE TITLE
gittyleaks found out that your apikey is visible!

### ISSUE THREAD

**Issue by kootenpv** [DataToInsight/TwitterAPI#1]
I'm the author of [gittyleaks](https://github.com/kootenpv/gittyleaks), and I wanted to bring it to your attention that even though you removed the twitter key from plain sight, it is still visible in the git history.

Just wanted to bring it up, as well as of course promote a little bit the importance of sensitive info in github (can still see into git history if not careful).

Have a look here about how to best handle it, good luck!

https://help.github.com/articles/remove-sensitive-data/

**Comment by wouteroosterbosch** [comment]
Thanks for the headsup and useful link kootenpv. Issue taken care of I believe.

**Comment by springcoil** [comment]
Thanks for that. Btw Wouter can you remove me from DataToInsight
ᐧ

On Mon, Aug 10, 2015 at 1:22 PM, Wouter Oosterbosch <
notifications@github.com> wrote:

> Thanks for the headsup and useful link kootenpv. Issue taken care of I
> believe.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DataToInsight/TwitterAPI/issues/1#issuecomment-129411491
> .

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by wouteroosterbosch** [comment]
I did over a year ago. But this was a public repo that you created, hence the subscription to the individual repo.

**Comment by springcoil** [comment]
Hey Wouter - I deleted that repo since I wasn't using it. Thanks :)
ᐧ

On Mon, Aug 10, 2015 at 1:31 PM, Wouter Oosterbosch <
notifications@github.com> wrote:

> I did over a year ago. But this was a public repo that you created, hence
> the subscription to the individual repo.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DataToInsight/TwitterAPI/issues/1#issuecomment-129413346
> .

## 

Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by kootenpv** [comment]
Indeed, I can confirm it has been solved :)
